name: Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build and package Electron app
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload release assets
        id: release                  
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload built files
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./dist/CodeAnchorTechDocs Setup 0.1.0.exe
          asset_name: CodeAnchorTechDocs Setup 0.1.0.exe
          asset_content_type: application/octet-stream
